### ISSUE TITLE
MySQL 8 not configured properly on V7

### ISSUE THREAD

**Issue by rupikakapoor** [engineyard/ey-cookbooks-dev-v7#152]
MySQL version 8 is not getting configured properly on stack-v7:

* /etc/alternatives/my.cnf is pointed to wrong place
* The /db volume on v7 mysql 8 is empty, data is in /var/lib/mysql instead

**Comment by dvalfre** [comment]
Tracked internally on FBZ-10514

**Comment by rupikakapoor** [comment]
Not being released in stable-v7-1.0.11, as this is still being worked upon. Work can be tracked through branch  [fbz-10514-MySQL8-not-properly-configured](https://github.com/engineyard/ey-cookbooks-stable-v7/tree/fbz-10514-MySQL8-not-properly-configured)

**Comment by herbertia** [comment]
Do you have any update on this issue? We are in process to migrate our stack to v7 but I am afraid that it won't be stable with this bug in case we have to boot a new DB in emergency.
Thanks for the update

**Comment by rupikakapoor** [comment]
Fix Released stable-v7-1.0.14
