### ISSUE TITLE
ClamAV Jobs are ignored, while being executed as a cron

### ISSUE THREAD

**Issue by pasanchamikara** [engineyard/ey-cookbooks-dev-v7#168]
ClamAV jobs are getting correctly completed once manually set. However, once they are run as Cronjobs, they do not get completed due to the date parameter that we pass

**Comment by pasanchamikara** [comment]
PR added https://github.com/engineyard/ey-cookbooks-stable-v7/pull/170

**Comment by rupikakapoor** [comment]
fix released in stable-v7-1.0.13
