### ISSUE TITLE
Add support for Postgresql version > 11 from Dashboard 

### ISSUE THREAD

**Issue by rupikakapoor** [engineyard/ey-cookbooks-dev-v7#173]
Add support for Postgresql version > 11 from Dashboard

**Comment by rupikakapoor** [comment]
Internally tacked on FBZ-10532

**Comment by dvalfre** [comment]
Just to comment, until this issue is addressed, versions of PG > 11 can still be setup using env var `EY_POSTGRES_VERSION`.
The use of the env var remains true for customers who want to set a specific minor version, as the recipes otherwise install the latest minor version.

**Comment by rupikakapoor** [comment]
Fix released in stable-v7-1.0.13
