### ISSUE TITLE
Update environment variables document to include EY_POSTGRES_VERSION

### ISSUE THREAD

**Issue by dvalfre** [engineyard/ey-cookbooks-dev-v7#174]
The doc at https://github.com/engineyard/ey-cookbooks-stable-v7/blob/next-release/EnvironmentVariables.md can do with an update on how to use `EY_POSTGRES_VERSION`.

**Comment by rupikakapoor** [comment]
Fixed -PR #185

**Comment by rupikakapoor** [comment]
released stable-v7-1.0.14
