### ISSUE TITLE
ClamAV scheduling parameters are recognized as Strings while implementing custom cron scheduling

### ISSUE THREAD

**Issue by pasanchamikara** [engineyard/ey-cookbooks-dev-v7#177]
During Custom Cron scheduling of ClamAV cookbook, the environment variables (`EY_CLAMAV_RUNHOUR` and `EY_CLAMAV_RUNMINUTE`) to schedule timing are passed as strings.

**Comment by pasanchamikara** [comment]
PR created https://github.com/engineyard/ey-cookbooks-stable-v7/pull/176

**Comment by rupikakapoor** [comment]
Released on #stable-v7-1.0.13
