### ISSUE TITLE
MySQL server is installed and started on app and util instances

### ISSUE THREAD

**Issue by dvalfre** [engineyard/ey-cookbooks-dev-v7#198]
Turns out that mysqld is installed and running on app and util instances when it shouldn't be

Spotted on MySQL 5.7, stable-v7-1.0.15, replicated internally with MySQL 8.

**Comment by eudalov** [comment]
Released in https://github.com/engineyard/ey-cookbooks-stable-v7/releases/tag/stable-v7-1.0.17.
