### ISSUE TITLE
Env vars EY_SIDEKIQ_* not installing Sidekiq on solo instance

### ISSUE THREAD

**Issue by rupikakapoor** [engineyard/ey-cookbooks-dev-v7#207]
Installing **sidekiq** using environment variables 

```
EY_SIDEKIQ_ENABLED = TRUE
EY_SIDEKIQ_INSTANCES_ROLE = solo
```

Not installing sidekiq on solo instance, as a side note this get installed after adding custom-sidekiq recipe with attribute `default['sidekiq']['is_sidekiq_instance'] = (node['dna']['instance_role'] == 'solo')`. 

So, I suspect conditions at https://github.com/engineyard/ey-cookbooks-stable-v7/blob/next-release/cookbooks/ey-sidekiq/attributes/default.rb#L8-L10 are missing solo somehow.

**Comment by eudalov** [comment]
Released in https://github.com/engineyard/ey-cookbooks-stable-v7/releases/tag/stable-v7-1.0.17.
