### ISSUE TITLE
Chef does not know about MySQL version 8.0.28 

### ISSUE THREAD

**Issue by dvalfre** [engineyard/ey-cookbooks-dev-v7#208]
Turns out that the Percona repositories no longer host version 8.0.28 of MySQL for Ubuntu, which is the default version installed by these recipes. [This line](https://github.com/engineyard/ey-cookbooks-stable-v7/blob/next-release/cookbooks/ey-mysql/attributes/version.rb#L5) has to be updated to 8.0.29.

Until a fix is in place, please set environment variable `EY_MYSQL_VERSION=8.0.29` and hit Apply on the failing instances.

**Comment by scottsherwood** [comment]
@dvalfre As it looks like you have identified the issue here, would it be possible to push a permanent fix for this out soon please?

**Comment by dvalfre** [comment]
Upstream has deprecated version 8.0.29 as well, so the minimum version has to be set at 8.0.30.

**Comment by dvalfre** [comment]
The smart way to handle this will be to autodetect the lower minor version available at all times. This _could be_ achieved by modifying [here](https://github.com/engineyard/ey-cookbooks-stable-v7/blob/next-release/cookbooks/ey-mysql/attributes/version.rb#L4-L5) with something like [this code](https://github.com/engineyard/ey-cookbooks-stable-v7/blob/next-release/cookbooks/ey-mysql/recipes/install.rb#L24).

**Comment by scottsherwood** [comment]
8.0.30 appears to be deprecated now too, so switched to 8.0.31

**Comment by eudalov** [comment]
Released in https://github.com/engineyard/ey-cookbooks-stable-v7/releases/tag/stable-v7-1.0.17.
