### ISSUE TITLE
Enabling HTTP2 causes invalid nginx config (Ruby/Puma)

### ISSUE THREAD

**Issue by sfnelson** [engineyard/ey-cookbooks-dev-v7#94]
https://github.com/engineyard/ey-cookbooks-stable-v7/blob/next-release/cookbooks/ey-nginx/recipes/ruby.rb#L34

```
        http2: node["nginx"]["http2"],
        ssl: !(count == 0)
```

If HTTP2 is enabled via a custom recipe, then this combination of settings causes an invalid nginx server configuration in https://github.com/engineyard/ey-cookbooks-stable-v7/blob/next-release/cookbooks/ey-nginx/templates/default/nginx_app.conf.erb#L29

```
  <% if @http2 %>
    listen <%= @haproxy_nginx_port %> ssl http2 proxy_protocol;
  <% else %>
    listen <%= @haproxy_nginx_port %> proxy_protocol;
    listen <%= @xlb_nginx_port %> ;
  <% end %>
```

HTTP2 requires SSL, but the recipe is used to create both the SSL and non-SSL versions of this file. This leads to a server block with the invalid configuration of requiring http2 but not providing a certificate.

This appears to be a regression caused by incorrectly combining two template blocks. See https://github.com/engineyard/ey-cookbooks-stable-v6/blob/next-release/cookbooks/nginx/recipes/default.rb#L154 where http2 is false when SSL is false.

Proposed fix:

Change the template to `<% if @ssl && @http2 %>` or change the recipe to `http2: node["nginx"]["http2"] && !(count == 0)`

**Comment by mushyy** [comment]
Hi @sfnelson. Excellent point. Thanks for the pull request appreciate it
